### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by realquantumcookie** [InteractivePlus/TechDoc#1]
This will be a LTS list for the team to track work in this repo.

**Comment by realquantumcookie** [comment]
Time: 2022-05-25
Finished: 2022-05-25 PST

- InteractiveSSO
  - [x] OAuth2.0 Authorize API for frontend to communicate with backend.
  - [x] Let User List, Search, Manage(Edit + Delete) ALL OAuth2.0 Records (Authorization only, not tokens)
  - [x] Admin functionality on OAuth2.0

No admin option will be developed for user token and oauth token because we might be using JWT implementations on those ones.

After that, I think the API definition is pretty much done. We just need to implement the backend and the frontend
